

--Create Date:        2021-06-22
--Author:             Beingnin

DECLARE @QUERY NVARCHAR(200)='';

DECLARE C CURSOR

FOR SELECT 'DROP '+ROUTINE_TYPE+' '+ROUTINE_SCHEMA+'.'+ ROUTINE_NAME FROM INFORMATION_SCHEMA.ROUTINES WHERE ROUTINE_SCHEMA='xAudit'
OPEN C
FETCH NEXT FROM C INTO @QUERY
WHILE @@FETCH_STATUS=0
BEGIN
	EXEC(@QUERY);
	FETCH NEXT FROM C INTO @QUERY;
END
CLOSE C;
DEALLOCATE C


