--Create Date:        2021-06-22
--Author:             Beingnin

DECLARE @QUERY NVARCHAR(200)='';

DECLARE C CURSOR

FOR 
SELECT 'DROP '+ROUTINE_TYPE+' ['+ROUTINE_SCHEMA+'].['+ ROUTINE_NAME+']' FROM INFORMATION_SCHEMA.ROUTINES WHERE ROUTINE_SCHEMA='xAudit' 
UNION ALL
SELECT 'DROP TYPE [xAudit].['+ [NAME]+']' FROM SYS.TYPES WHERE [SCHEMA_ID]= SCHEMA_ID('xAudit')
OPEN C
FETCH NEXT FROM C INTO @QUERY
WHILE @@FETCH_STATUS=0
BEGIN
	EXEC(@QUERY);
	FETCH NEXT FROM C INTO @QUERY;
END
CLOSE C;
DEALLOCATE C